### ISSUE TITLE
[refactor] collection pages

### ISSUE THREAD

**Issue by gweiying** [isomerpages/isomercms-frontend#585]
## Tasks

- [x] Add React Query hooks for collection pages (CRUD)
- [x] Add V2 endpoints for collection pages (CRUD)
- [x] Update EditPage 
  - [x] Use React Query hooks (RUD)
  - [x] May need to add other hooks apart from collection pages
  - [x] EditPage tidy up 
- [x] Update EditPage URL params 
- [x] Update Cypress tests for EditPage

**Comment by gweiying** [comment]
closed by #602 #603
