### ISSUE TITLE
[CLEANUP] Post-identity cleanup for code cleanliness

### ISSUE THREAD

**Issue by seaerchin** [isomerpages/isomercms-frontend#849]
tagging @alexanderleegs in case i missed something out

### Problem 
Identity had a bunch of PRs by different authors - this meant that there were some areas of the codebase that are unclear due to the massive scope of work. A best effort non-exhaustive list will be provided below

- [x] `fixtures/identity` vs `test/constants` 
- [x] using `res.locals` instead of setting properties on req
- [x] isomerpages/isomercms-backend#400 
- [x] isomerpages/isomercms-backend#396 
- [x] isomerpages/isomercms-backend#395 
- [x] isomerpages/isomercms-backend#387 
- [x] isomerpages/isomercms-backend#356
